/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2026-07-19 16:43:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dasbord_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Sports Management Dashboard</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            /* Beautiful online hockey turf/stadium wallpaper */\r\n");
      out.write("            background: linear-gradient(rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.75)), \r\n");
      out.write("            url('image/dasbord.png') no-repeat center center fixed;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            color: white;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column; /* Fixed: Dashboard top-to-bottom layout me rahega */\r\n");
      out.write("        }\r\n");
      out.write("        /* Header Navigation */\r\n");
      out.write("        .header {\r\n");
      out.write("            background: linear-gradient(135deg, #1e3c72 0%, #88b314 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px 40px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            box-shadow: 0 4px 15px rgba(0,0,0,0.3);\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        .header h1 {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("        .logout-btn {\r\n");
      out.write("            background-color: #ff4757;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .logout-btn:hover {\r\n");
      out.write("            background-color: #ff6b81;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(255, 71, 87, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("        /* Main Container */\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 40px auto;\r\n");
      out.write("            padding: 0 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .welcome-text {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            color: #ffffff; /* Improved contrast over dark bg */\r\n");
      out.write("            text-shadow: 2px 2px 4px rgba(0,0,0,0.5);\r\n");
      out.write("        }\r\n");
      out.write("        /* Grid Layout for Cards (Left to Right) */\r\n");
      out.write("        .grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\r\n");
      out.write("            gap: 25px;\r\n");
      out.write("        }\r\n");
      out.write("        /* Beautiful Dashboard Cards */\r\n");
      out.write("        .card {\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 25px 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(0,0,0,0.3);\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column; /* Fixed: Text and Subtext stack vertically */\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            min-height: 140px;\r\n");
      out.write("        }\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: translateY(-8px);\r\n");
      out.write("            box-shadow: 0 12px 25px rgba(0,0,0,0.4);\r\n");
      out.write("        }\r\n");
      out.write("        .card span {\r\n");
      out.write("            font-size: 22px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            letter-spacing: 0.5px;\r\n");
      out.write("            text-shadow: 1px 1px 2px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("        /* Different Colors for Different Sports/Modules */\r\n");
      out.write("        .cricket { background: linear-gradient(135deg, #3b7515, #c2831e); }\r\n");
      out.write("        .football { background: linear-gradient(135deg, #1b1747, #27ae60); }\r\n");
      out.write("        .hockey { background: linear-gradient(135deg, #abad26, #d35400); }\r\n");
      out.write("        .teams { background: linear-gradient(135deg, #ad7ac2, #8e44ad); }\r\n");
      out.write("        .players { background: linear-gradient(135deg, #8cb6d1, #2980b9); }\r\n");
      out.write("        .matches { background: linear-gradient(135deg, #86b1a8, #16a085); }\r\n");
      out.write("        .score { background: linear-gradient(135deg, #d18279, #c0392b); }\r\n");
      out.write("        \r\n");
      out.write("        .card-subtext {\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            opacity: 0.9;\r\n");
      out.write("            margin-top: 8px;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            letter-spacing: 0.5px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Top Navigation Bar -->\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <h1>🏆 Sports Management System</h1>\r\n");
      out.write("        <a href=\"logout.jsp\" class=\"logout-btn\">Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content Area -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 class=\"welcome-text\">Welcome to Admin Dashboard</h2>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"grid\">\r\n");
      out.write("            <!-- Cricket Card -->\r\n");
      out.write("            <a href=\"cricket.jsp\" class=\"card cricket\">\r\n");
      out.write("                <span>Cricket</span>\r\n");
      out.write("                <div class=\"card-subtext\">Manage Cricket Data</div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Football Card -->\r\n");
      out.write("            <a href=\"football.jsp\" class=\"card football\">\r\n");
      out.write("                <span>Football</span>\r\n");
      out.write("                <div class=\"card-subtext\">Manage Football Data</div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Hockey Card -->\r\n");
      out.write("            <a href=\"hockey.jsp\" class=\"card hockey\">\r\n");
      out.write("                <span>Hockey</span>\r\n");
      out.write("                <div class=\"card-subtext\">Manage Hockey Data</div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Teams Card -->\r\n");
      out.write("            <a href=\"team.jsp\" class=\"card teams\">\r\n");
      out.write("                <span>Teams</span>\r\n");
      out.write("                <div class=\"card-subtext\">View & Edit Teams</div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Players Card -->\r\n");
      out.write("            <a href=\"player.jsp\" class=\"card players\">\r\n");
      out.write("                <span>Players</span>\r\n");
      out.write("                <div class=\"card-subtext\">Manage All Players</div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Matches Card -->\r\n");
      out.write("            <a href=\"match.jsp\" class=\"card matches\">\r\n");
      out.write("                <span>Matches</span>\r\n");
      out.write("                <div class=\"card-subtext\">Schedule Matches</div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Score Card -->\r\n");
      out.write("            <a href=\"score.jsp\" class=\"card score\">\r\n");
      out.write("                <span>Score Board</span>\r\n");
      out.write("                <div class=\"card-subtext\">Live Scores & Standings</div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
