/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2026-07-19 16:57:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model.Player;

public final class player_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Player");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Player Details</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap');\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            /* Premium Dark Stadium theme overlay ke sath */\r\n");
      out.write("            background: linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.85)), \r\n");
      out.write("                        url('image/player.png') no-repeat center center fixed;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 40px 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Glassmorphism Profile Dashboard Wrapper */\r\n");
      out.write("        .dashboard-container {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.07);\r\n");
      out.write("            backdrop-filter: blur(12px);\r\n");
      out.write("            -webkit-backdrop-filter: blur(12px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.15);\r\n");
      out.write("            padding: 35px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 750px;\r\n");
      out.write("            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.5);\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 2.2rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            letter-spacing: 2px;\r\n");
      out.write("            text-shadow: 0 4px 10px rgba(0,0,0,0.4);\r\n");
      out.write("            border-bottom: 2px solid #007bff; /* Blue Accent for Player Board */\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding-bottom: 6px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Form Layout Style */\r\n");
      out.write("        .player-form {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 18px;\r\n");
      out.write("            max-width: 480px;\r\n");
      out.write("            margin: 0 auto 40px auto;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group label {\r\n");
      out.write("            width: 110px;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("            background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            color: #111111;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            transition: border-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group input:focus {\r\n");
      out.write("            border-color: #007bff;\r\n");
      out.write("            box-shadow: 0 0 8px rgba(0, 123, 255, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Premium Save Button */\r\n");
      out.write("        .btn-submit {\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            background: linear-gradient(135deg, #007bff, #0056b3);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0, 123, 255, 0.3);\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-submit:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(0, 123, 255, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Modern Table Design */\r\n");
      out.write("        .table-wrapper {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            overflow-x: auto;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.03);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 8px 16px rgba(0,0,0,0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 14px 16px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th {\r\n");
      out.write("            background: linear-gradient(135deg, #212529, #343a40);\r\n");
      out.write("            color: #007bff;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("            border-bottom: 2px solid rgba(255,255,255,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        td {\r\n");
      out.write("            color: #e0e0e0;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.08);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tr:hover td {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.07);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tr:last-child td {\r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .no-data {\r\n");
      out.write("            color: #ffc107;\r\n");
      out.write("            font-style: italic;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("    <div class=\"dashboard-container\">\r\n");
      out.write("        <h2>Player Details</h2>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Form Section -->\r\n");
      out.write("        <!-- Sahi servlet url mapping check kar lena (jaise PlayerServlet ya jo bhi aapka hai) -->\r\n");
      out.write("        <form action=\"PlayerServlet\" method=\"POST\" class=\"player-form\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"name\">Name</label>\r\n");
      out.write("                <input type=\"text\" id=\"name\" name=\"name\" placeholder=\"Enter Player Name\">\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"age\">Age</label>\r\n");
      out.write("                <input type=\"number\" id=\"age\" name=\"age\" placeholder=\"Enter age (8-60)\">\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"team\">Team</label>\r\n");
      out.write("                <input type=\"text\" id=\"team\" name=\"team\" placeholder=\"Enter Team Name\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <button type=\"submit\" class=\"btn-submit\">Save Player</button>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <!-- Dynamic Table Section -->\r\n");
      out.write("        <div class=\"table-wrapper\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>ID</th>\r\n");
      out.write("                        <th>Name</th>\r\n");
      out.write("                        <th>Age</th>\r\n");
      out.write("                        <th>Team</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");
 
                        // Controller/Servlet se aane waali list handle ki ja rahi hai
                        List<Player> playerList = (List<Player>) request.getAttribute("playerList");
                        
                        if (playerList != null && !playerList.isEmpty()) {
                            for (Player p : playerList) {
                    
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>");
      out.print( p.getId() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( p.getPlayerName() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( p.getAge() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( p.getTeam() );
      out.write("</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                    ");
 
                            }
                        } else { 
                    
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td colspan=\"4\" class=\"no-data\">No players registered yet!</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                    ");
 
                        } 
                    
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("            <a href=\"dasbord.jsp\" class=\"back-btn\">← Back to Main Dashboard</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
