/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2026-07-19 16:57:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import model.Team;

public final class score_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Team");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Score Board</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Google Fonts se modern font load kiya */\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap');\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            /* Premium Dark Sports Background overlay ke sath */\r\n");
      out.write("            background: linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.85)), \r\n");
      out.write("                        url('image/score.png') no-repeat center center fixed;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Glassmorphism Effect Container */\r\n");
      out.write("        .score-container {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.08);\r\n");
      out.write("            backdrop-filter: blur(12px);\r\n");
      out.write("            -webkit-backdrop-filter: blur(12px);\r\n");
      out.write("            border: 1px solid rgba(255, 255, 255, 0.15);\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 2.2rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            letter-spacing: 3px;\r\n");
      out.write("            text-shadow: 0 4px 10px rgba(0,0,0,0.5);\r\n");
      out.write("            border-bottom: 2px solid #007bff;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding-bottom: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive & Modern Table Design */\r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: collapse;\r\n");
      out.write("            margin-bottom: 35px;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.03);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 8px 16px rgba(0,0,0,0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 16px 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        th {\r\n");
      out.write("            background: linear-gradient(135deg, #007bff, #0056b3);\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        td {\r\n");
      out.write("            color: #e8e8e8;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            border-bottom: 1px solid rgba(255, 255, 255, 0.08);\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hover effect rows par */\r\n");
      out.write("        tr:hover td {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.08);\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        tr:last-child td {\r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* No Data Message Styling */\r\n");
      out.write("        .no-data {\r\n");
      out.write("            color: #ffc107;\r\n");
      out.write("            font-style: italic;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Back Button Design */\r\n");
      out.write("        .btn-back {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 12px 35px;\r\n");
      out.write("            background: transparent;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            border: 2px solid #ffffff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-back:hover {\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            color: #111111;\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(255, 255, 255, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"score-container\">\r\n");
      out.write("        <h2>Score Board</h2>\r\n");
      out.write("        \r\n");
      out.write("        <table>\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>Team Name</th>\r\n");
      out.write("                    <th>Sport Type</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                ");
 
                    // Servlet se bheji gayi list ko nikal rahe hain
                    List<Team> teamList = (List<Team>) request.getAttribute("teamList");
                    
                    if (teamList != null && !teamList.isEmpty()) {
                        // Loop chala kar saari teams ko display kar rahe hain
                        for (Team t : teamList) {
                
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>");
      out.print( t.getTeamName() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( t.getSport() );
      out.write("</td> \r\n");
      out.write("                            </tr>\r\n");
      out.write("                ");
 
                        }
                    } else { 
                
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"2\" class=\"no-data\">No teams registered yet!</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                ");
 
                    } 
                
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"team.jsp\" class=\"btn-back\">Back</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
